# Generated by Django 5.2.1 on 2025-05-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tableSample',
            fields=[
                ('recordNo', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=200)),
            ],
            options={
                'db_table': 'table_sample',
            },
        ),
    ]
