# Generated by Django 5.2.1 on 2025-06-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesample',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tablesample',
            name='recordNo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
